name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: controlepedidos-cpfregister
  AZURE_FUNCTIONAPP_RG: controlepedidos-rg 
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: CpfRegisterFunction
  PACKAGE_ZIP: functionapp.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build project
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish project with Functions metadata
        run: |
          dotnet publish "${{ env.WORKING_DIRECTORY }}" \
            --configuration ${{ env.CONFIGURATION }} \
            --output ./published \
            /p:GenerateFunctions=true
      - name: Zip published folder
        run: |
          cd published
          zip -r ../${{ env.PACKAGE_ZIP }} *
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: ${{ env.PACKAGE_ZIP }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp
          path: .

      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop Azure Function App
        run: |
          az functionapp stop --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_FUNCTIONAPP_RG }}

      - name: Deploy files to Azure Function App (Linux)
        run: |
          az webapp deploy \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --resource-group ${{ env.AZURE_FUNCTIONAPP_RG }} \
            --src-path ${{ env.PACKAGE_ZIP }} \
            --type zip

      - name: Start Azure Function App
        run: |
          az functionapp start --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_FUNCTIONAPP_RG }}