name: Build and Deploy Azure Functions

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore CpfRegisterFunction/CpfRegisterFunction.csproj

      - name: Build and Publish
        run: |
          dotnet publish CpfRegisterFunction/CpfRegisterFunction.csproj \
            --configuration Release \
            --output ./publish/cpfregister
      - name: Zip package
        run: |
          cd publish
          zip -r cpfregister.zip cpfregister

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    
      - name: Deploy Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: "controlepedidos-cpfregister"
          package: "./publish/cpfregister.zip"
